### PR TITLE
fixed not saving of downloaded content

### PR DESCRIPTION
**Pull request by RythenGlyth**
fix of the error addressed in #87 and #86 

something went wrong with the mkfile method, so I switched to using fs' mkdir and now it's working (at least for me)

### CODE REVIEW

**Comment by DirgaBrajamusti** [comment]
Thanks for the fix, it works for me

**Comment by sobuj53** [comment]
Thank you very much for the fix, it's working perfectly now with Stack-20,
image

**Comment by chhayse7en** [comment]
Files uploaded to Gdrive are occasionally corrupted or incomplete files. Ex: Original file is 300MB in size but the uploaded file in Gdrive is 100MB in size.  another issue is the file always get zipped first in heroku before uploading to Gdrive.
problem

**Review by Ayan-Bhar — APPROVED** [review]

**Comment by patheticGeek** [comment]
@RythenGlyth Thanks for your time highly appreciated

**Pull request merged**
