### PR TITLE
Can this fix limetorrent issue?

### PR DESCRIPTION
**Pull request by Itz-fork**
Not sure! try yourself!

### CODE REVIEW

**Comment by sobuj53** [comment]
This fix doesn't work for me.

**Comment by sobuj53** [comment]
However it works sometimes, but I've also updated the config variable in Heroku, 
image
It doesn't work always but works on most cases,
image

**Comment by Hirusha-H** [comment]
> This fix doesn't work for me.

really? it's works fine for me!

**Comment by sobuj53** [comment]
> > This fix doesn't work for me.
> 
> really? it's works fine for me!

try `/search limetorrent Chernobyl`
and tell me what do you get?

**Comment by sobuj53** [comment]
Good for you. But it's not working for me unfortunately. I just redeploy my repo again but same. Turns out `/search limetorrent Chernobyl` is not working but other search command works just fine, weird 
image,
If you could mange some time, I'd request you to take a look at my repo if you don't mind. Thanks

**Comment by sobuj53** [comment]
> Good for you. But it's not working for me unfortunately. I just redeploy my repo again but same. Turns out `/search limetorrent Chernobyl` is not working but other search command works just fine, weird
> image,
> If you could mange some time, I'd request you to take a look at my repo if you don't mind. Thanks

I've found a wired phenomenon, if I search `/search limetorrent chernobyl` instead of `/search limetorrent Chernobyl` then it works 😕
image
if it's possible can you please make the search term convert to lower case letter regardless of user input? That would solve the issue for all I guess

**Comment by Hirusha-H** [comment]
> > Good for you. But it's not working for me unfortunately. I just redeploy my repo again but same. Turns out `/search limetorrent Chernobyl` is not working but other search command works just fine, weird
> > image,
> > If you could mange some time, I'd request you to take a look at my repo if you don't mind. Thanks
> 
> I've found a wired phenomenon, if I search `/search limetorrent chernobyl` instead of `/search limetorrent Chernobyl` then it works 
> image
> if it's possible can you please make the search term convert to lower case letter regardless of user input? That would solve the issue for all I guess

i think it can't be fixed! issue from LimeTorrent Site,

<a href="#"> </a>

and,

<a href="#"> </a>

**Comment by sobuj53** [comment]
yes but we can convert user input to lower-case eg. `var str = "Hello World!";
var res = str.toLowerCase();` but I'm not a coder so I don't know how to convert` {term}` to lowercase letter before we initiate the search.

**Comment by Hirusha-H** [comment]
> yes but we can convert user input to lower-case eg. `var str = "Hello World!"; var res = str.toLowerCase();` but I'm not a coder so I don't know how to convert` {term}` to lowercase letter before we initiate the search.

No luck with this! Sed lyf

**Comment by sobuj53** [comment]
https://www.limetorrents.info/search/all/{term}/ this works, thanks to #97 
set Config var in Heroku as, `LIMETORRENT_SITE` value= `https://www.limetorrents.info/search/all/{term}/ `

**Comment by patheticGeek** [comment]
This is the same issue with other proxies. Sometimes they are down, no guarantees of uptime

**Pull request closed without merging**
